global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: /metrics

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: /metrics

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8002']
    metrics_path: /metrics

  - job_name: 'wallet-service'
    static_configs:
      - targets: ['wallet-service:8004']
    metrics_path: /metrics

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8005']
    metrics_path: /metrics

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:8006']
    metrics_path: /metrics

  - job_name: 'ledger-service'
    static_configs:
      - targets: ['ledger-service:8007']
    metrics_path: /metrics

  - job_name: 'fraud-service'
    static_configs:
      - targets: ['fraud-service:8008']
    metrics_path: /metrics

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8009']
    metrics_path: /metrics
